apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o petclinic_chart/templates
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: mysql-server
  name: mysql-server
spec:
  # # RDS is a Pod in our kubernetes cluster.
  # ports:
  #   - name: "3306"
  #     port: 3306
  #     targetPort: 3306
  # selector:
  #   io.kompose.service: mysql-server

  # RDS is an AWS service.
  type: ExternalName # connecting to an external service (AWS RDS).
  externalName: petclinic.c0h1zpvnuper.us-east-1.rds.amazonaws.com # AWS RDS endpoint.
